### ISSUE TITLE
Install cpu-optimized version of Stockfish

### ISSUE THREAD

**Issue by fitztrev** [fitztrev/lichess-tauri#24]
Determine which CPU architecture client is using and install the optimized version from [the engine directory](https://fitztrev.github.io/lichess-tauri/engine-directory.json).

Right now, it's just installing the `default` version for each OS.

[This is the line](https://github.com/fitztrev/lichess-tauri/blob/d3dde516a72330d3f788f04b6591aa5872b73889/src-tauri/src/engine_directory.rs#L55) that needs to be changed.

**Comment by niklasf** [comment]
Here's how fishnet does this: https://github.com/lichess-org/fishnet/blob/d0990ef62422c86013270e768e5cb8724f4585f7/src/assets.rs#L98-L131
