### ISSUE TITLE
URLs don't open in Linux AppImage

### ISSUE THREAD

**Issue by Janbuller** [fitztrev/lichess-tauri#26]
I downloaded the v0.0.5 appimage from github releases, but when I tried to click the button to log in with lichess, it didn't open the url in my browser. I decided to try compiling it myself instead, so I could add a print statement to the oauth handler so it prints the url to stdout for copying, but, to my surprise, it just worked straight away after compiling.

**Comment by fitztrev** [comment]
Thanks for the report. Seeing the same thing. Works with the .deb but not the AppImage.

Looks like this might be the issue: https://github.com/tauri-apps/tauri/issues/6172
