### ISSUE TITLE
lichess-local-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SergioGlorias** [fitztrev/lichess-tauri#27]
it looks like `libssl.so.1.1` needs to be installed to use `.deb`
But newer Debian 12 and Ubuntu don't have this lib

**Comment by kevlu8** [comment]
This should help: https://stackoverflow.com/questions/72133316/

**Comment by SergioGlorias** [comment]
@kevlu8 
First you are asked to install one from Ubuntu 
According to this lib, it has already been discontinued in both Ubuntu and Debian 
Installing things that will no longer be updated can bring vulnerability to the system
