### ISSUE TITLE
v0.0.5 linux fails to log in to lichess

### ISSUE THREAD

**Issue by nbi1** [fitztrev/lichess-tauri#30]
Installed the v0.0.5 .deb package. Running lichess-local-engine and clicking the log in button produces a "Failed to execute default Web Browser" message (Input/Output Error). I run the latest versions of both FireFox and Chrome on my system. So whatever it's looking for one of these should satisfy it.

Just out of curiosity, what should be the permissions on /usr/bin/lichess-local-engine ?

Thanks.

**Comment by fitztrev** [comment]
Thanks. Will look into.

When I tested in #26, .deb links would open for me.

**Comment by fitztrev** [comment]
Can you try v0.0.6 and let me know if this is resolved for you? Links are opened in a different way now that may be more compatible.
